// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.nahid.grpc;

public interface APIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>int32 responseCode = 2;</code>
   */
  int getResponseCode();
}
