// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.nahid.grpc;

public interface RegistrationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegistrationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fullName = 1;</code>
   */
  java.lang.String getFullName();
  /**
   * <code>string fullName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>string userName = 2;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string phoneNumber = 3;</code>
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phoneNumber = 3;</code>
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>string email = 4;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 5;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 5;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
